309Project: test.c File Reference
test.c File Reference
#include <avr/io.h>
#include <util/delay.h>
Functions
void Init (void)
int main (void)
void Lights_run (void)
Variables
char run = 1
Function Documentation
void Init (void)
Initializes ports and variables
Referenced by main().
{
    DDRA = 0xFF;
    PORTA = 0x01;
}
void Lights_run (void)
Tests LED bank and PORTA
References run.
Referenced by main().
{
    while(run)
    {
        PORTA = PORTA << 1;
        _delay_ms(500);
    }
}
int main (void)
References Init(), and Lights_run().
{
    while(1)
    {
        Init();
        Lights_run();
    }
}
Variable Documentation
char run = 1
Referenced by Lights_run().